version: '3.9'

services:

  api:
    build: .
    container_name: flask-api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - DB_SERVER=sqlserver
      - DB_DATABASE=flaskdb
      - DB_USERNAME=sa
      - DB_PASSWORD=Senai@134
    networks:
      - flask-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Senai@134
    ports:
      - "1433:1433"
    networks:
      - flask-net

networks:
  flask-net:
    driver: bridge